apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: products
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: products
            port:
              number: 8080