apiVersion: v1
kind: Secret
metadata:
  name: postgres-creds
  labels:
    app: postgres
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_DB: products
  POSTGRES_PASSWORD: pgs3cr3t
  DATABASE_URI: "postgresql+psycopg://postgres:pgs3cr3t@postgres:5432/products"