apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: products-cd-pipeline
spec:
  params:
    - description: The URL to the git repo
      name: GIT_REPO
      type: string
    - default: master
      description: The reference (branch or ref)
      name: GIT_REF
      type: string
    - description: Fully qualified image to build/push/deploy (built in build stage, used by deploy)
      name: IMAGE_NAME
      type: string
      default: image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/products:latest
  tasks:
    - name: git-clone
      params:
        - name: CRT_FILENAME
          value: ca-bundle.crt
        - name: HTTP_PROXY
          value: ''
        - name: HTTPS_PROXY
          value: ''
        - name: NO_PROXY
          value: ''
        - name: SUBDIRECTORY
          value: ''
        - name: USER_HOME
          value: /home/git
        - name: DELETE_EXISTING
          value: 'true'
        - name: VERBOSE
          value: 'false'
        - name: SSL_VERIFY
          value: 'true'
        - name: URL
          value: $(params.GIT_REPO)
        - name: REVISION
          value: $(params.GIT_REF)
        - name: REFSPEC
          value: ''
        - name: SUBMODULES
          value: 'true'
        - name: DEPTH
          value: '1'
        - name: SPARSE_CHECKOUT_DIRECTORIES
          value: ''
      taskRef:
        params:
          - name: kind
            value: task
          - name: name
            value: git-clone
          - name: namespace
            value: openshift-pipelines
        resolver: cluster
      workspaces:
        - name: output
          workspace: products-pipeline-workspace
    - name: lint
      runAfter:
        - git-clone
      taskRef:
        name: pylint
        kind: Task
      params:
        - name: path
          value: "./service"
        - name: args
          value:
            - --max-line-length=127
      workspaces:
        - name: source
          workspace: products-pipeline-workspace
    - name: tests
      runAfter:
        - git-clone
      taskRef:
        name: pytest-env
        kind: Task
      params:
        - name: pytest-args
          value:
            - "-v"
            - "--cov=service"
        - name: secret-name
          value: "postgres-creds"
        - name: secret-key
          value: "DATABASE_URI"
      workspaces:
        - name: source
          workspace: products-pipeline-workspace
    - name: build
      runAfter:
        - lint
        - tests
      taskRef:
        params:
          - name: kind
            value: task
          - name: name
            value: buildah
          - name: namespace
            value: openshift-pipelines
        resolver: cluster
      params:
        - name: IMAGE
          value: $(params.IMAGE_NAME)
        - name: DOCKERFILE
          value: ./Dockerfile
        - name: CONTEXT
          value: .
        - name: TLSVERIFY
          value: "false"
        - name: STORAGE_DRIVER
          value: vfs
      workspaces:
        - name: source
          workspace: products-pipeline-workspace
    - name: deploy
      runAfter:
        - build
      taskRef:
        name: deploy-image
        kind: Task
      params:
        - name: image-name
          value: $(params.IMAGE_NAME)
      workspaces:
        - name: source
          workspace: products-pipeline-workspace
  workspaces:
    - name: products-pipeline-workspace
  finally: []
